services:
  web:
    build: .
    container_name: hotel_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: hotel_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
